### ISSUE TITLE
Players cannot pickup items in lands when ranked even when ITEM_PICKUP is true in config and lands admin menu.

### ISSUE THREAD

**Issue by Bettanation** [Angeschossen/Lands#13]
Server Version: 1.16.4 Latest
Lands Version: 4.11.1

Players cannot pickup items in lands when ranked even when default is true in config.

For example if they are member rank in a land that just got created, even with the item_pickup as true in the config for all ranks it doesnt work, and has to be manually changed by the land owner or me, which is not fun to do constantly.

This needs to be fixed, as this Item_Pickup flag is a decision maker on wether or not to keep your plugin, as ive said its not fun to deal with constantly.

**Comment by Angeschossen** [comment]
Thank you for your feedback! In recent versions it will copy the values from the member (entry) role of the land (so if they make changes to this role and then create a new role, it will initially copy the flags over to the new role).
