### ISSUE TITLE
Iron golem can be killed in claim

### ISSUE THREAD

**Issue by Bettanation** [Angeschossen/Lands#17]
Iron golem can be killed in claim by random players with arrows and there is no way to stop this.
I dont know if they can be killed with swords or etc, havent done that much testing.
They are passive until they are attacked and players are upset about losing iron golems to other players.

**Comment by Angeschossen** [comment]
Iron golems can be attacked, because they will attack the attacker (player).
I'll add a attack monster flag in future which will toggle mobs being able to attack players and reverse.

**Comment by Angeschossen** [comment]
A flag for this has been added.
