### ISSUE TITLE
(Suggestion) Add support for Pl3xmap

### ISSUE THREAD

**Issue by LichLord91** [Angeschossen/Lands#19]
Pl3xmap is a new map program made by the same team that makes Purpur, a fork of Tuinity. Great bunch of devs and the map is coming along very nicely. I suspect it'll grow quite popular. I'd love to see Lands integrated in it.

https://github.com/pl3xgaming/Pl3xMap 

Feel free to see my map as an example 

https://map.lichcraft.games/ 

https://github.com/pl3xgaming/Pl3xMap/issues/18

**Comment by Angeschossen** [comment]
Has been added. :)

**Comment by LichLord91** [comment]
Awesome ill take a look!
