### ISSUE TITLE
Players invincible to all damage except zombies and pvp

### ISSUE THREAD

**Issue by Molkars** [Angeschossen/Lands#22]
This may be a config or permission on my end but I have been trying to figure this out for a couple of days. I am running a Geyser-Paper 1.16.5 server. I have looked through the wiki and haven't found anything about invincibility. While I am running other plugins in addition to this one, I have isolated the issue to this plugin (uninstall a plugin and reload until we are no longer invincible.)

The plugin throws no errors nor logs any warnings during runtime. I am using Luckyperms as my permission system and vault with BoostEconomy as my economy plugin.

**Comment by EkonC** [comment]
I can confirm this. It only happens in the world that I have enabled Lands in.

**Comment by Angeschossen** [comment]
Please make sure to check that the invincible flag is disabled in /lands admin wilderness.

**Comment by Molkars** [comment]
Yeah turning on the invulnerable flag worked for me.
